app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/','FrontController@login');
Route::get('inicio','FrontController@app');
Route::get('logout','LoginController@logout');
//Route::get('unidades','FrontController@unidadesMedida');

//Route::get('crear-usuario','FrontController@createUsers');

Route::resource('login','LoginController');
Route::resource('user','UserController');
Route::resource('proveedores','ProveedorController');
Route::resource('clientes','ClienteController');
Route::resource('unidades-medida','UnidadMedidaController');
Route::resource('materiales','MaterialController');
Route::resource('marcas','MarcaController');
Route::resource('colores','ColorController');
Route::resource('oficios','OficioController');
Route::resource('maquinas','MaquinaController');
Route::resource('categoria-referencia','CategoriaReferenciaController');
Route::resource('categoria-insumo','CategoriaInsumoController');
Route::resource('categoria-material','CategoriaMaterialController');
Route::resource('referencias','ReferenciaController');
Route::resource('insupros','InsuproController');
Route::resource('laminas','LaminaController');
Route::resource('insumos','InsumoController');
Route::resource('cotizaciones','CotizacionController');

Route::get('referencias/codigo-elemento-referencia/{id}','ReferenciaController@getCodigoReferenciaElementos');
Route::get('proveedor-material/{tabla}/{tablaRel}/{colIdRel}/{id}','MaterialController@getProveedoresMateriales');
Route::get('proveedor-lamina/{tabla}/{tablaRel}/{colIdRel}/{id}','LaminaController@getProveedoresLaminas');
Route::get('proveedor-insumo/{tabla}/{tablaRel}/{colIdRel}/{id}','InsumoController@getProveedoresInsumos');
Route::get('img-referencia/{id}','ReferenciaController@getImagenReferencia');

Route::get('insumos/busqueda-proveedores-insumos/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('insumos/{id}/busqueda-proveedores-insumos/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('laminas/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('laminas/{id}/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('materiales/busqueda-proveedores-materiales/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('laminas/{id}/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('referencia-insupros/insupros/{id}','ReferenciaController@getInsupros');
//================================================================================
//Agregar elementos a las piezas
Route::post('insupros/agregar-piezas/{idInsupro}','InsuproController@guardarPiezasInsupro');
Route::post('insupros/agregar-insumos-insupro/{idInsupro}','InsuproController@guardarInsumosInsupro');
Route::post('insupros/agregar-confecciones-insupro/{idInsupro}','InsuproController@guardarConfeccionesInsupro');
Route::post('insupros/agregar-oficios-varios-insupro/{idInsupro}','InsuproController@guardarOficiosInsupro');

Route::get('cotizaciones/valores-referencia/{idReferencia}','CotizacionController@getValuesInsupro');

resources/views/admin/admin.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align border-bottom title-wrrapper">
            <h5 class="important bold">Administrador</h5>
        </div>
        <div class="col s3 center-align admin-btn-wrapper">
        	<ul class="admin-ul-buttons">
            <li> {!! link_to('user', $title = 'Ver usuarios', $parameters = array('class'=>'waves-effect waves-light btn'), $attributes = array()) !!}</li>
        		<li> {!! link_to('user/create', $title = 'Crear usuario', $parameters = array('class'=>'waves-effect waves-light btn'), $attributes = array()) !!}</li>
        	</ul>	
      	</div>

      <div class="col s9 border-left">
			   @yield('contentAdmin')
      </div>
    </div>
	
@stop

resources/views/admin/create-users.blade.php
@extends('admin.admin')

@section('contentAdmin')
    <!-- Dropdown Structure -->
    <div class="row">

        <div class="col s12 left-align">
            <h5 class="important regular">Crear nuevo usuario</h5>
        </div>

        <div class="col s12 center-align">
            {!! Form::open(array('route' => 'user.store','method' => 'POST','class'=>'col s12')) !!}
                @include('admin.include_form-user',['titleBtn' => 'Registrar']);
            {!! Form::close() !!}


        </div>


   
         <div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso">
            @if(Session::get('message') == 'store')
                <h6>Usuario creado </h6>       
            @endif      
        </div>

    </div>
	
@stop

resources/views/admin/edit-user.blade.php
@extends('admin.admin')

@section('contentAdmin')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 left-align">
            <h5 class="important regular">Editar usuario</h5>
        </div>

        <div class="col s12 center-align">
            {!! Form::model($user,array('route' => ['user.update',$user->id],'method'=>'PUT','class'=>'col s12')) !!}

                @include('admin.include_form-user',['titleBtn' => 'Modificar']);

                {!! Form::close() !!}

    	</div>


   
        <div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso">
            @if(Session::has('message'))
                <h6>Usuario modificado </h6>       
            @endif      
        </div>
    </div>
@stop

resources/views/admin/include_form-user.blade.php
<div class="col s12 m12 l6">
    <div class="input-field col s12">
        <i class="material-icons prefix">assignment_ind</i>
        {!! Form::text('nombre',null, array('class' => 'validate','id' => 'icon_prefix')) !!}
        {!! Form::label('icon_prefix', 'Nombre...')  !!}

        {!! $errors->first('nombre', "<span class='error'>:message</span>") !!}
    </div>

                    <div class="input-field col s12">
        <i class="material-icons prefix">assignment_ind</i>
        {!! Form::text('apellido',null, array('class' => 'validate','id' => 'icon_lastname')) !!}
        {!! Form::label('icon_lastname', 'Apellido...')  !!}

        {!! $errors->first('apellido', "<span class='error'>:message</span>") !!}
    </div>
     
    <div class="input-field col s12">
        <i class="material-icons prefix">account_circle</i>
            {!! Form::text('usuario',null, array('class' => 'validate','id' => 'icon_username')) !!}
        {!! Form::label('icon_username', 'Nombre usuario...')  !!}

        {!! $errors->first('usuario', "<span class='error'>:message</span>") !!}
    </div>
</div>

<div class="col s6">
        <div class="input-field col s12">
        <i class="material-icons prefix">lock</i>
        {!! Form::password('password', array('class' => 'validate','id' => 'icon_password')) !!}
        {!! Form::label('icon_password', 'Contraseña...')  !!}

        {!! $errors->first('password', "<span class='error'>:message</span>") !!}
    </div>
    <div class="input-field col s12">
        <i class="material-icons prefix">lock</i>
        {!! Form::password('password_confirmation', array('class' => 'validate','id' => 'icon_password_repeat')) !!}
        {!! Form::label('icon_password_repeat', 'Repetir Contraseña...')  !!}

        {!! $errors->first('password_confirmation', "<span class='error'>:message</span>") !!}
    </div>
    <div class="col s12 m12 l12 right-align">
        {!! Form::submit($titleBtn,array("class" => "btn margin-btn-form")) !!}
    </div>
</div>

resources/views/admin/view-users.blade.php
@extends('admin.admin')

@section('contentAdmin')
    <!-- Dropdown Structure -->
    <div class="row">

    	@if(Session::has('message'))
     		<div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso">
               {{Session::get('message')}}           
        	</div>
        @endif 
        <div class="col s12 left-align">
            <h5 class="important regular">Ver Usuarios</h5>
        </div>
		
		<div class="col s12 left-align">
	        <table>
		        <thead >
		          	<tr>
			            <th data-field="id"  class="center-align">Nombre</th>
			            <th data-field="name"  class="center-align">Apellido</th>
			            <th data-field="price"  class="center-align">Usuario</th>
			            <th data-field="price"  class="center-align">Modificar</th>
			            <th data-field="price"  class="center-align">Eliminar</th>
		          	</tr>
		        </thead>
			    <tbody>
			    	@foreach ($usuarios as $usuario)
			          	<tr  class="center-align">
				            <td  class="center-align">{{$usuario->usuario}}</td>
				            <td  class="center-align">{{$usuario->nombre}}</td>
				            <td  class="center-align">{{$usuario->apellido}}</td>
				            <td  class="center-align">
							{!! link_to_route('user.edit', $title = 'Editar', $parameters = $usuario->id, $attributes = array()) !!}

				            <i class="material-icons">mode_edit</i></td>
				            <td  class="center-align"><i class="material-icons">delete</i></td>
			          	</tr>
					@endforeach
			    </tbody>
	      </table>
      </div>
    </div>
	
@stop