app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/','FrontController@login');
Route::get('inicio','FrontController@app');
Route::get('logout','LoginController@logout');
//Route::get('unidades','FrontController@unidadesMedida');

//Route::get('crear-usuario','FrontController@createUsers');

Route::resource('login','LoginController');
Route::resource('user','UserController');
Route::resource('proveedores','ProveedorController');
Route::resource('clientes','ClienteController');
Route::resource('unidades-medida','UnidadMedidaController');
Route::resource('materiales','MaterialController');
Route::resource('marcas','MarcaController');
Route::resource('colores','ColorController');
Route::resource('oficios','OficioController');
Route::resource('maquinas','MaquinaController');
Route::resource('categoria-referencia','CategoriaReferenciaController');
Route::resource('categoria-insumo','CategoriaInsumoController');
Route::resource('categoria-material','CategoriaMaterialController');
Route::resource('referencias','ReferenciaController');
Route::resource('insupros','InsuproController');
Route::resource('laminas','LaminaController');
Route::resource('insumos','InsumoController');
Route::resource('cotizaciones','CotizacionController');

Route::get('referencias/codigo-elemento-referencia/{id}','ReferenciaController@getCodigoReferenciaElementos');
Route::get('proveedor-material/{tabla}/{tablaRel}/{colIdRel}/{id}','MaterialController@getProveedoresMateriales');
Route::get('proveedor-lamina/{tabla}/{tablaRel}/{colIdRel}/{id}','LaminaController@getProveedoresLaminas');
Route::get('proveedor-insumo/{tabla}/{tablaRel}/{colIdRel}/{id}','InsumoController@getProveedoresInsumos');
Route::get('img-referencia/{id}','ReferenciaController@getImagenReferencia');

Route::get('insumos/busqueda-proveedores-insumos/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('insumos/{id}/busqueda-proveedores-insumos/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('laminas/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('laminas/{id}/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('materiales/busqueda-proveedores-materiales/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('laminas/{id}/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('referencia-insupros/insupros/{id}','ReferenciaController@getInsupros');
//================================================================================
//Agregar elementos a las piezas
Route::post('insupros/agregar-piezas/{idInsupro}','InsuproController@guardarPiezasInsupro');
Route::post('insupros/agregar-insumos-insupro/{idInsupro}','InsuproController@guardarInsumosInsupro');
Route::post('insupros/agregar-confecciones-insupro/{idInsupro}','InsuproController@guardarConfeccionesInsupro');
Route::post('insupros/agregar-oficios-varios-insupro/{idInsupro}','InsuproController@guardarOficiosInsupro');

Route::get('cotizaciones/valores-referencia/{idReferencia}','CotizacionController@getValuesInsupro');

app/Http/Controllers/LaminaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\LaminaRequest;
use App\Http\Requests\LaminaUpdateRequest;
use App\Entities\Lamina;
use App\Entities\Proveedor;
use App\Helpers\HelperFunctions;
use Session;
use Redirect;
use DB;

class LaminaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $laminas = Lamina:: 
        select('*')
        ->where('estado',1)       
        ->orderBy('id', 'asc')
        ->paginate(20);
      
        return view('laminas.lamina',['laminas' => $laminas]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $proveedor = Proveedor:: 
        select('empresa','id')
        ->where('estado',1)        
        ->orderBy('id', 'asc')
        ->get();
        return view('laminas.create-lamina',['proveedores'=>$proveedor]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(LaminaRequest $request)
    {
        DB::table('laminas')->insert([
            'nombre'  => $request['nombre'],
            'ancho'   => $request['ancho'],
            'largo'   => $request['largo'],
            'precio'  => $request['precio'],
        ]);
      
        //--------------------------------------------------
        //--------------------------------------------------
        $hProveedorMaterial = new HelperFunctions();
        $idLamina = $hProveedorMaterial->getLastIdTable('laminas')->id;
        //Verifica si existe la variable de proveedores, en caso de
        if(isset($request['proveedores-list'])){
          $hProveedorMaterial->insertProveedoresTabla('laminas_proveedores',$idLamina,$request['proveedores-list'],'laminas','id_lamina');
        }
        else{
         return "fallo";
        }
      
        return redirect('laminas/create')->with('message','store');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $proveedor = Proveedor:: 
        select('empresa','id')
        ->where('estado',1)        
        ->orderBy('id', 'asc')
        ->get();
        
        //Helper
        $hProveedorMaterial = new HelperFunctions();
        $proveedorLista =  $hProveedorMaterial->getProveedoresTabla('laminas',$id,'laminas_proveedores','id_lamina');
        //-----------------------------------------------------------------
        $lamina = Lamina::find($id);

        return view('laminas.edit-lamina',['lamina'=>$lamina,'proveedoresList'=>$proveedorLista,'proveedores'=>$proveedor]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(LaminaUpdateRequest $request, $id)
    {
        $lamina = Lamina::find($id);
        $lamina->fill($request->all());
        $lamina->save();
      
        $hProveedorLaminas = new HelperFunctions();
        //Verifica si existe la variable de proveedores, en caso de
        if(isset($request['proveedores-list'])){
            $hProveedorLaminas->insertProveedoresTabla('laminas_proveedores',$id,$request['proveedores-list'],'laminas','id_lamina');
        }

        Session::flash('message','La lamina ha sido editada correctamente');
        return Redirect::to('/laminas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
  
     public function getProveedoresLaminasDinamico(Request $request,$palabra){
      $hProveedorMaterial = new HelperFunctions();
      $proveedorLista =  $hProveedorMaterial->getProveedoresTablaDinamico($palabra);

        if($request->ajax()){
            return response()->json($proveedorLista);
        }else{
          return "Error";
        }
    }
  
  
   public function getProveedoresLaminasDinamicoEdit(Request $request,$id,$palabra){
      $hProveedorMaterial = new HelperFunctions();
      $proveedorLista =  $hProveedorMaterial->getProveedoresTablaDinamico($palabra);

        if($request->ajax()){
            return response()->json($proveedorLista);
        }else{
          return "Error";
        }
    }

  
   /**
     * Retrive specific info.
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   public function getProveedoresLaminas(Request $request,$tabla,$tablaRel,$colIdRel,$id){
      $hProveedorMaterial = new HelperFunctions();
      $proveedorLista =  $hProveedorMaterial->getProveedoresTabla($tabla,$id,$tablaRel,$colIdRel);

        if($request->ajax()){
            return response()->json($proveedorLista);
        }else{
          return $tabla." ".$tablaRel." ".$colIdRel." ".$id;
        }
    }
}

resources/views/laminas/create-lamina.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">Crear Laminas</h5>
        </div>
      @include('includes.include_mensaje-creado',['mensaje' => 'Material creado'])
        <div class="col s12 center-align">
             {!! Form::open(array('route' => 'laminas.store','method' => 'POST','class'=>'col s12')) !!}

                @include('laminas.include_form-lamina',['titleBtn' => 'Crear'])

            {!! Form::close() !!}

    	</div>

       @include('includes.include_mensaje-creado',['mensaje' => 'Material creado'])
    </div>
@stop

resources/views/laminas/edit-lamina.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">Editar Laminas</h5>
        </div>

        <div class="col s12 center-align">
            {!! Form::model($lamina,array('route' => ['laminas.update',$lamina->id],'method'=>'PUT','class'=>'col s12')) !!}

                @include('laminas.include_form-lamina',['titleBtn' => 'Modificar'])

            {!! Form::close() !!}
    	</div>
    </div>
    
    <!-- ===================================== -->
    <div class="col s12">
        <hr class="orange-line" />
    </div>

    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">Lista Proveedores</h5>
        </div>
        <div class="col s12 center-align">
            <table>
                <thead >
                    <tr>
                        <th data-field="id"  class="center-align">Código</th>
                        <th data-field="name"  class="center-align">Empresa</th>
                        <th data-field="price"  class="center-align">Eliminar</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($proveedoresList as $proveedoList)
                        <tr  class="center-align">
                            <td  class="center-align">{{$proveedoList->id}}</td>
                            <td  class="center-align">{{$proveedoList->empresa}}</td>
                            <td  class="center-align">{!! link_to_route('proveedores.edit', $title = 'Borrar', $parameters = $proveedoList->id, $attributes = array('class'=>'btn red darken-3')) !!}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    
        <div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso center-align">
            @if(Session::has('message'))
                <h6>Material editado </h6>       
            @endif      
        </div>
    </div>
@stop

resources/views/laminas/include_form-lamina.blade.php
<!-- ================================================== -->
<!-- Macro create for use collection from model Country -->
{!! Form::macro( 'DBSelect', function($fieldName, $collection, $options=array('id' => 'empresa')){ $key = key($options); $rows = $collection->lists($options[$key], $key ); return Form::select($fieldName, $rows,null,array('class' => 'validate select-custom','id'
=> 'icon_country'),array('multiple')); }) !!}


<div class="col s12 m12 l6 offset-l3 center-align">

  <div class="input-field col s12 center-align">
    {!! Form::text('nombre',null, array('class' => 'validate','id' => 'nombre')) !!} {!! Form::label('nombre', 'Nombre lamina...') !!} {!! $errors->first('nombre', "<span class='error center-align'>:message</span>") !!}
  </div>

  <div class="input-field col s12 center-align">
    {!! Form::text('ancho',null, array('class' => 'validate','id' => 'ancho')) !!} {!! Form::label('ancho', 'Ancho lamina...') !!} {!! $errors->first('ancho', "<span class='error center-align'>:message</span>") !!}
  </div>

  <div class="input-field col s12 center-align">
    {!! Form::text('largo',null, array('class' => 'validate','id' => 'largo')) !!} {!! Form::label('largo', 'Largo lamina...') !!} {!! $errors->first('largo', "<span class='error center-align'>:message</span>") !!}
  </div>

  <div class="input-field col s12 center-align">
    {!! Form::text('precio',null, array('class' => 'validate','id' => 'precio')) !!} {!! Form::label('precio', 'Precio lamina...') !!} {!! $errors->first('precio', "<span class='error center-align'>:message</span>") !!}
  </div>

  <!-- ================================================== -->
  <!-- Proveedores -->
  <div class="input-field col s7">
    <select id="prov-laminas" multiple name="proveedores-list[]" class='custom-scroll'>
      <option value="" disabled selected>Escoge el o los proveedores</option>
      @foreach($proveedores as $proveedor)
      <option value='{{$proveedor->id}}'>{{$proveedor->empresa}}</option>
      @endforeach
    </select>

    {!! $errors->first('proveedores-list[]', "<span class='error'>:message</span>") !!}
  </div>
  <div class="input-field col s5">
    <input id="serch-prov-laminas" type="text" class="validate search-dina" data-nombre="laminas" data-id-select="prov-laminas">
    <label for="serch-material">Buscar proveedors</label>
  </div>
  <!--
  <div class="input-field col s5">
    <input id="serch-pro-laminas" type="text" class="validate search" data-id-select="prov-laminas">
    <label for="serch-pro-laminas">Buscar en material</label>
  </div>
  -->
  <div class="col s12 m12 l6 center-align">
    {!! link_to('laminas', $title = 'Volver', $parameters = array("class" => "btn margin-btn-form btn-40"), $attributes = array()) !!}
  </div>

  <div class="col s12 m12 l6 center-align">
    {!! Form::submit($titleBtn,array("class" => "btn margin-btn-form btn-40")) !!}
  </div>

</div>

resources/views/laminas/lamina.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">Laminas</h5>
        </div>

        <div class="s12 center-align">
           {!! link_to('laminas/create', $title = 'Agregar Lamina', $parameters = array("class" => "btn margin-btn-form"), 
       		$attributes = array()) !!}
        </div>
        
    </div>
     <div class="row">
    	@if(Session::has('message'))
     		<div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso">
               {{Session::get('message')}}           
        	</div>
        @endif 
	
		<div class="col s12 center-align">
           <h6 class="bold">Cantidad registros: {!! $laminas->total() !!}</h6>
    		{!! $laminas->render() !!}
        </div>

		<div class="col s12 ">
	        <table>
		        <thead >
		          	<tr>
			            <th data-field="id"  class="center-align">Código</th>
			            <th data-field="name"  class="center-align">Nombre</th>
			            <th data-field="name"  class="center-align">Ancho</th>
			            <th data-field="name"  class="center-align">Largo</th>
			            <!--<th data-field="price"  class="center-align">Fecha creación</th>-->
			            <th data-field="price"  class="center-align">Precio</th>
									<th data-field="price"  class="center-align">Última Modificación</th>
			            <th data-field="price"  class="center-align">Modificar</th>
			            <th data-field="price"  class="center-align">Eliminar</th>
		          	</tr>
		        </thead>
			    <tbody>
			    	@foreach ($laminas as $lamina)
			          	<tr  class="center-align">
				            <td  class="center-align">{{$lamina->id}}</td>
				            <td  class="center-align">{{$lamina->nombre}}</td>
				            <td  class="center-align">$ {{$lamina->ancho}}</td>
				            <td  class="center-align">{{$lamina->largo}}</td>
										<td  class="center-align">{{$lamina->precio}}</td>
										<td  class="center-align">{{$lamina->updated_at}}</td>
				            <td  class="center-align ver-proveedores" data-proveedor="lamina" data-ver="{{$lamina->id}}"  data-nombre="{{$lamina->nombre}}" data-tabla="laminas" data-tabla-rel="laminas_proveedores" data-id-param="id_lamina" ><a class=" waves-effect waves-light btn">Proveedores</a></td>
				    				<td class="center-align"> {!! link_to_route('laminas.edit', $title = 'Editar', $parameters = $lamina->id, $attributes = array('class'=>'btn ')) !!}</td>
				  					<td  class="center-align">{!! link_to_route('laminas.edit', $title = 'Borrar', $parameters = $lamina->id, $attributes = array('class'=>'btn red darken-3')) !!}</td>
			          	</tr>
					@endforeach
			    </tbody>
	      	</table>
      	</div>
    </div>
  
    <div class="col s12 center-align">
        <h6 class="bold">Cantidad registros: {!! $laminas->total() !!}</h6>
    	{!! $laminas->render() !!}
    </div>

  <!-- Modal Structure -->
  <div id="modal1" class="modal modal-fixed-footer">
    <div class="modal-content center-align">
			   <h5  class="important regular bold" id="titulo-material"> </h5>
     		 <h5  class="">Lista de Proveedores</h5>
       	<table>
					<thead >
							<tr>
								<th data-field="id"  class="center-align">Código</th>
								<th data-field="name"  class="center-align">Empresa</th>
								<th data-field="name"  class="center-align">Direccion</th>
								<th data-field="price"  class="center-align">Teléfono</th>
								<th data-field="price"  class="center-align">Celular</th>
								<th data-field="price"  class="center-align">Email</th>
							</tr>
					</thead>
			    <tbody id="result-materiales">
			    </tbody>
	      </table>
    </div>
		<div class="modal-footer center-align">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Cerrar</a>
    </div>
	</div>
@stop