app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::get('/','FrontController@login');
Route::get('inicio','FrontController@app');
Route::get('logout','LoginController@logout');
//Route::get('unidades','FrontController@unidadesMedida');

//Route::get('crear-usuario','FrontController@createUsers');

Route::resource('login','LoginController');
Route::resource('user','UserController');
Route::resource('proveedores','ProveedorController');
Route::resource('clientes','ClienteController');
Route::resource('unidades-medida','UnidadMedidaController');
Route::resource('materiales','MaterialController');
Route::resource('marcas','MarcaController');
Route::resource('colores','ColorController');
Route::resource('oficios','OficioController');
Route::resource('maquinas','MaquinaController');
Route::resource('categoria-referencia','CategoriaReferenciaController');
Route::resource('categoria-insumo','CategoriaInsumoController');
Route::resource('categoria-material','CategoriaMaterialController');
Route::resource('referencias','ReferenciaController');
Route::resource('insupros','InsuproController');
Route::resource('laminas','LaminaController');
Route::resource('insumos','InsumoController');
Route::resource('cotizaciones','CotizacionController');

Route::get('referencias/codigo-elemento-referencia/{id}','ReferenciaController@getCodigoReferenciaElementos');
Route::get('proveedor-material/{tabla}/{tablaRel}/{colIdRel}/{id}','MaterialController@getProveedoresMateriales');
Route::get('proveedor-lamina/{tabla}/{tablaRel}/{colIdRel}/{id}','LaminaController@getProveedoresLaminas');
Route::get('proveedor-insumo/{tabla}/{tablaRel}/{colIdRel}/{id}','InsumoController@getProveedoresInsumos');
Route::get('img-referencia/{id}','ReferenciaController@getImagenReferencia');

Route::get('insumos/busqueda-proveedores-insumos/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('insumos/{id}/busqueda-proveedores-insumos/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('laminas/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('laminas/{id}/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('materiales/busqueda-proveedores-materiales/{palabra}','LaminaController@getProveedoresLaminasDinamico');
Route::get('laminas/{id}/busqueda-proveedores-laminas/{palabra}','LaminaController@getProveedoresLaminasDinamicoEdit');

Route::get('referencia-insupros/insupros/{id}','ReferenciaController@getInsupros');
//================================================================================
//Agregar elementos a las piezas
Route::post('insupros/agregar-piezas/{idInsupro}','InsuproController@guardarPiezasInsupro');
Route::post('insupros/agregar-insumos-insupro/{idInsupro}','InsuproController@guardarInsumosInsupro');
Route::post('insupros/agregar-confecciones-insupro/{idInsupro}','InsuproController@guardarConfeccionesInsupro');
Route::post('insupros/agregar-oficios-varios-insupro/{idInsupro}','InsuproController@guardarOficiosInsupro');

Route::get('cotizaciones/valores-referencia/{idReferencia}','CotizacionController@getValuesInsupro');

resources/views/colores/color.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">colores</h5>
        </div>


        <div class="s12 center-align">
           {!! link_to('colores/create', $title = 'Agregar color', $parameters = array("class" => "btn margin-btn-form"), 
       $attributes = array()) !!}
        </div>
    </div>
     <div class="row">
    	@if(Session::has('message'))
     		<div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso">
               {{Session::get('message')}}           
        	</div>
        @endif 
	
		<div class="col s12 center-align">
           <h6 class="bold">Cantidad registros: {!! $colores->total() !!}</h6>
    		{!! $colores->render() !!}
        </div>
     
		
		<div class="col s12 ">
	        <table>
		        <thead >
		          	<tr>
			            <th data-field="id"  class="center-align">Código</th>
			            <th data-field="name"  class="center-align">Nombre</th>
			            <th data-field="price"  class="center-align">Fecha creación</th>
			            <th data-field="price"  class="center-align">Fecha Modificación</th>
			            <th data-field="price"  class="center-align">Modificar</th>
			            <th data-field="price"  class="center-align">Eliminar</th>
		          	</tr>
		        </thead>
			    <tbody>
			    	@foreach ($colores as $color)
			          	<tr  class="center-align">
				            <td  class="center-align">{{$color->id}}</td>
				            <td  class="center-align">{{$color->nombre}}</td>
				            <td  class="center-align">{{$color->created_at}}</td>
				            <td  class="center-align">{{$color->updated_at}}</td>
				            <td  class="center-align">
												{!! link_to_route('colores.edit', $title = 'Editar', $parameters = $color->id, $attributes = array('class'=>'btn ')) !!}</td>
				  <td  class="center-align">{!! link_to_route('colores.edit', $title = 'Borrar', $parameters = $color->id, $attributes = array('class'=>'btn red darken-3')) !!}</td>
			          	</tr>
					@endforeach
			    </tbody>
	      </table>
      </div>
    </div>
    <div class="col s12 center-align">
        <h6 class="bold">Cantidad registros: {!! $colores->total() !!}</h6>
    	{!! $colores->render() !!}
    </div>
@stop

resources/views/colores/create-color.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">Crear color</h5>
        </div>

        @include('includes.include_mensaje-creado',['mensaje' => 'Color creado'])

        <div class="col s12 center-align">
             {!! Form::open(array('route' => 'colores.store','method' => 'POST','class'=>'col s12')) !!}

                @include('colores.include_form-color',['titleBtn' => 'Crear'])

                {!! Form::close() !!}

    	</div>

        @include('includes.include_mensaje-creado',['mensaje' => 'Color creado'])
    </div>
@stop

resources/views/colores/edit-color.blade.php
@extends('layouts.main_app')

@section('content')
    <!-- Dropdown Structure -->
    <div class="row">
        <div class="col s12 center-align">
            <h5 class="important regular">Editar colores</h5>
        </div>

        <div class="col s12 center-align">
            {!! Form::model($color,array('route' => ['colores.update',$color->id],'method'=>'PUT','class'=>'col s12')) !!}

                @include('colores.include_form-color',['titleBtn' => 'Modificar'])

                {!! Form::close() !!}

    	</div>

        <div class="col offset-s4 s4 center-align card-panel  light-green darken-1 exitoso center-align">
            @if(Session::has('message'))
                <h6>Color editado </h6>       
            @endif      
        </div>
    </div>
@stop

resources/views/colores/include_form-color.blade.php
<div class="col s12 m12 l6 offset-l3 center-align">
    <div class="input-field col s12 center-align">
        {!! Form::text('nombre',null, array('class' => 'validate','id' => 'nombre')) !!}
        {!! Form::label('nombre', 'Nombre color...')  !!}

        {!! $errors->first('nombre', "<span class='error center-align'>:message</span>") !!}
    </div>

    <div class="col s12 m12 l12 center-align">
        {!! Form::submit($titleBtn,array("class" => "btn margin-btn-form btn-40")) !!}
    </div>

    <div class="col s12 m12 l12 center-align">
       {!! link_to('colores', $title = 'Volver', $parameters = array("class" => "btn margin-btn-form btn-40"), 
       $attributes = array()) !!}
    </div>
</div>